# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-23 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('f_link', models.CharField(max_length=200, null=True)),
                ('t_link', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
