# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-23 15:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cm1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id1', models.CharField(max_length=12)),
                ('contact_id1', models.CharField(max_length=12)),
                ('status', models.IntegerField(choices=[(0, 'Followed'), (1, 'Pending'), (2, 'Connected'), (3, 'Declined'), (4, 'Blocked')], default=0)),
                ('mute_notification', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(db_column='contact_id', on_delete=django.db.models.deletion.CASCADE, related_name='user__contacts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TempContactPhoneChangeNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_country_code', models.CharField(blank=True, max_length=50, null=True)),
                ('old_phone_num', models.CharField(max_length=100)),
                ('old_display_num', models.CharField(max_length=150)),
                ('new_country_code', models.CharField(blank=True, max_length=50, null=True)),
                ('new_phone_num', models.CharField(max_length=100)),
                ('new_display_num', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tct_phone_change_notification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Temp Contact Phone Num Change Notifications',
            },
        ),
        migrations.CreateModel(
            name='UserJoinedNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joining_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_joining_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_joining_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Joined Notifications',
            },
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set([('user', 'contact')]),
        ),
    ]
