# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-24 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cm1', '0002_auto_20170323_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=200)),
                ('l_name', models.CharField(blank=True, max_length=200, null=True)),
                ('other_phone', models.IntegerField(max_length=12, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.CharField(blank=True, max_length=500, null=True)),
                ('cover_photo', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.SmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True)),
                ('dob', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempContactEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(db_index=True, max_length=200)),
                ('email_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_media_source', models.CharField(choices=[('', ''), ('_Propagated', '_Propagated'), ('Facebook', 'Facebook'), ('GooglePlus', 'GooglePlus'), ('LinkedIn', 'LinkedIn'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('Pinterest', 'Pinterest'), ('Foursquare', 'Foursquare')], default='', max_length=50)),
                ('temp_id', models.CharField(max_length=12)),
                ('is_edit_notif_rejected', models.BooleanField(default=False)),
                ('is_merge_notif_rejected', models.BooleanField(default=False)),
                ('temp_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_contact_emails', to='cm1.TempContact')),
            ],
        ),
        migrations.CreateModel(
            name='TempContactNickName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_media_source', models.CharField(choices=[('', ''), ('_Propagated', '_Propagated'), ('Facebook', 'Facebook'), ('GooglePlus', 'GooglePlus'), ('LinkedIn', 'LinkedIn'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('Pinterest', 'Pinterest'), ('Foursquare', 'Foursquare')], default='', max_length=50)),
                ('is_add_attr', models.BooleanField(default=False)),
                ('temp_id', models.CharField(max_length=12)),
                ('temp_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_contact_nicknames', to='cm1.TempContact')),
            ],
        ),
        migrations.CreateModel(
            name='TempContactOtherAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(max_length=50)),
                ('other_account', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_media_source', models.CharField(choices=[('', ''), ('_Propagated', '_Propagated'), ('Facebook', 'Facebook'), ('GooglePlus', 'GooglePlus'), ('LinkedIn', 'LinkedIn'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('Pinterest', 'Pinterest'), ('Foursquare', 'Foursquare')], default='', max_length=50)),
                ('temp_id', models.CharField(max_length=12)),
                ('temp_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_contact_other_accounts', to='cm1.TempContact')),
            ],
        ),
        migrations.CreateModel(
            name='TempContactPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('phone_number', models.CharField(db_index=True, max_length=100)),
                ('display_number', models.CharField(max_length=150)),
                ('international_number', models.CharField(max_length=150)),
                ('phone_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_media_source', models.CharField(choices=[('', ''), ('_Propagated', '_Propagated'), ('Facebook', 'Facebook'), ('GooglePlus', 'GooglePlus'), ('LinkedIn', 'LinkedIn'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('Pinterest', 'Pinterest'), ('Foursquare', 'Foursquare')], default='', max_length=50)),
                ('temp_id', models.CharField(max_length=12)),
                ('is_edit_notif_rejected', models.BooleanField(default=False)),
                ('temp_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_contact_phones', to='cm1.TempContact')),
            ],
        ),
        migrations.CreateModel(
            name='TempContactPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_title', models.CharField(blank=True, max_length=500, null=True)),
                ('picture_url', models.URLField(blank=True, max_length=500, null=True)),
                ('cdn_key', models.CharField(blank=True, max_length=500, null=True)),
                ('type', models.SmallIntegerField(choices=[(1, 'Profile Picture'), (2, 'Cover Photo')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempContactSocialAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media', models.CharField(max_length=50)),
                ('social_account', models.CharField(max_length=500)),
                ('social_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_media_source', models.CharField(choices=[('', ''), ('_Propagated', '_Propagated'), ('Facebook', 'Facebook'), ('GooglePlus', 'GooglePlus'), ('LinkedIn', 'LinkedIn'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('Pinterest', 'Pinterest'), ('Foursquare', 'Foursquare')], default='', max_length=50)),
                ('temp_id', models.CharField(max_length=12)),
                ('temp_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_contact_social_accounts', to='cm1.TempContact')),
            ],
        ),
        migrations.CreateModel(
            name='TempContactWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('url_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_media_source', models.CharField(choices=[('', ''), ('_Propagated', '_Propagated'), ('Facebook', 'Facebook'), ('GooglePlus', 'GooglePlus'), ('LinkedIn', 'LinkedIn'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('Pinterest', 'Pinterest'), ('Foursquare', 'Foursquare')], default='', max_length=50)),
                ('temp_id', models.CharField(max_length=12)),
                ('temp_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_contact_websites', to='cm1.TempContact')),
            ],
        ),
        migrations.AddField(
            model_name='tempcontact',
            name='cover_picture',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_contact_cover_picture', to='cm1.TempContactPicture'),
        ),
        migrations.AddField(
            model_name='tempcontact',
            name='profile_picture',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_contact_profile_picture', to='cm1.TempContactPicture'),
        ),
    ]
